
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://capmjkvzgqgrceirvtfi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNhcG1qa3Z6Z3FncmNlaXJ2dGZpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM4NzMzNzcsImV4cCI6MjA1OTQ0OTM3N30.cTIrqv_atYw3tQnf2w-YrFkbW26fakKDiV__UqfIbtY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    persistSession: true,
    autoRefreshToken: true,
    storage: localStorage
  }
});
